cmake-project: add support for choosing the Qt version (5, 6 or none)
Usage: cmake-project [ -q | --qt 5 | 6 | none ]
Change-Id: I895c0b1c160846a9a456d5b05cb294414bacaef7
Reviewed-on: https://codereview.kdab.com/c/kdab/KDToolBox/+/102592
Tested-by: Continuous Integration <build@kdab.com>
Reviewed-by: Albert Astals Cid <albert.astals.cid@kdab.com>
Reviewed-by: Sérgio Martins <sergio@kdab.com>

diff --git a/qt/cmake-project/cmake-project b/qt/cmake-project/cmake-project
--- a/qt/cmake-project/cmake-project
+++ b/qt/cmake-project/cmake-project
@@ -5,6 +5,33 @@
 # Generate a CMakeLists.txt based on the .cpp files in the current directory
 # Similar to qmake -project, in essence.
 
+
+usage()
+{
+  echo "Usage: $0 [ -q | --qt 5 | 6 | none ]"
+  echo "The -q or --qt option allows to choose between Qt 5, Qt 6, or no Qt dependency"
+  exit 2
+}
+
+PARSED_ARGUMENTS=$(getopt -a -n cmake-project -o q:,h --long qt:,help -- "$@")
+INVALID_ARGUMENTS=$?
+if [ "$INVALID_ARGUMENTS" != "0" ]; then
+  usage
+fi
+
+eval set -- "$PARSED_ARGUMENTS"
+
+QTVERSION=5
+while :
+do
+  case "$1" in
+    -q | --qt)   QTVERSION="$2"      ; shift 2  ;;
+    -h | --help) usage; ;;
+    --) shift; break;;
+    *) echo "Unexpected option: $1"; usage; ;; # can't happen
+  esac
+done
+
 if [ -f CMakeLists.txt ]; then
     echo "CMakeLists.txt already exists, aborting for safety reasons"
     exit 1
@@ -16,26 +43,42 @@ if [ -z "$FILES" ]; then
 fi
 PROJECTNAME=`basename "$PWD" | sed -e 's/ /_/g'`
 TARGET="$PROJECTNAME"
-QT=Qt5
-QTLIBS="Core Gui"
-QTTARGETS="$QT::Core $QT::Gui"
-if [ -n "`grep QApplication *.cpp`" ]; then
-    QTLIBS="$QTLIBS Widgets"
-    QTTARGETS="$QTTARGETS $QT::Widgets"
-    AUTOUIC="set(CMAKE_AUTOUIC TRUE)"
+
+if [ "$QTVERSION" != "none" ]; then
+    QT=Qt$QTVERSION
+    QTLIBS="Core Gui"
+    QTTARGETS="$QT::Core $QT::Gui"
+    if [ -n "`grep QApplication *.cpp`" ]; then
+        QTLIBS="$QTLIBS Widgets"
+        QTTARGETS="$QTTARGETS $QT::Widgets"
+        AUTOUIC="set(CMAKE_AUTOUIC TRUE)"
+    fi
 fi
 
 cat > CMakeLists.txt <<EOF
 project($PROJECTNAME)
 cmake_minimum_required(VERSION 3.9)
 set(CMAKE_CXX_STANDARD 11)
-find_package($QT CONFIG REQUIRED COMPONENTS $QTLIBS)
 set(CMAKE_INCLUDE_CURRENT_DIR ON)
+EOF
+
+if [ "$QTVERSION" != "none" ]; then
+cat >> CMakeLists.txt <<EOF
+find_package($QT CONFIG REQUIRED COMPONENTS $QTLIBS)
 set(CMAKE_AUTOMOC TRUE)
 set(CMAKE_AUTORCC TRUE)
 $AUTOUIC
+EOF
+fi
+
+cat >> CMakeLists.txt <<EOF
 add_executable($PROJECTNAME
 $FILES
 )
+EOF
+
+if [ "$QTVERSION" != "none" ]; then
+cat >> CMakeLists.txt <<EOF
 target_link_libraries($PROJECTNAME $QTTARGETS)
 EOF
+fi
